#!/usr/bin/env bash
echo "Welcome!!"
echo "lets get started.."
echo "....installing git...."
sudo apt-get install git
if [ $? != 0 ]; then                   
   echo "Unsuccessful" 
else
   echo "git successfully installed"
fi


echo "....installing VLC...."
sudo add-apt-repository ppa:videolan/master-daily
sudo apt install vlc
if [ $? != 0 ]; then                   
   echo "Unsuccessful" 
else
   echo "VLC successfully installed"
fi


echo "....installing Python...."
sudo add-apt-repository ppa:fkrull/deadsnakes
sudo apt-get update
sudo apt-get install python2.7
if [ $? != 0 ]; then                   
   echo "Unsuccessful" 
else
   echo "Python successfully installed"
fi


echo "....installing Chrome...."
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get update 
sudo apt-get install google-chrome-stable
if [ $? != 0 ]; then                   
   echo "Unsuccessful" 
else
   echo "chrome successfully installed"
fi



echo "....installing sublime text...."
sudo add-apt-repository ppa:webupd8team/sublime-text-3
sudo apt-get update
sudo apt-get install sublime-text-installer
if [ $? != 0 ]; then                   
   echo "Unsuccessful" 
else
   echo "sublime text successfully installed"
fi


echo "....installing vim...."
sudo apt-get install vim
if [ $? != 0 ]; then                   
   echo "Unsuccessful" 
else
   echo "vim successfully installed"
fi

echo "....installing Oh my zsh and powerline...."
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
cp ~/.zshrc ~/.zshrc.orig
cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
chsh -s /bin/zsh
sudo apt-get install python-pip
pip install --user git+git://github.com/Lokaltog/powerline
if [ $? != 0 ]; then                   
   echo "Unsuccessful" 
else
   echo "zsh and powerline successfully installed"
fi


echo "Thank You For Using This Script!!"

